project:
  type: website
  output-dir: docs

website:
  title: "Yewon Kang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true


