project:
  type: website
  output-dir: docs

website:
  title: "Yewon Kang"
  navbar:
    left:
      - href: index.qmd
        text: About
      - research.qmd
  page-footer:
    background: dark
    left: "Yewon Kang © 2025"
    right: "Built with <a href='https://quarto.org/docs/websites/'>Quarto</a>"
        
format:
  html:
    theme: lux
    css: styles.css
    toc: true


